name: s07 Annotated tag, single hop

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@int
        with:
          egress-policy: audit
      - name: Action under test
        uses: tushar-stepsecurity/icd-test-action@v1-annotated
