name: s11 checkout releases/v4 head

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@int
        with:
          egress-policy: audit
      - name: Action under test
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
